### ISSUE TITLE
[Question] Support for Customized BaseFeaturesExtractor

### ISSUE THREAD

**Issue by kingjin94** [DLR-RM/rl-baselines3-zoo#411] opened 2023-10-19 15:26 UTC
### ❓ Question

I have implemented a FeatureExtractor as suggested in https://stable-baselines3.readthedocs.io/en/master/guide/custom_policy.html#custom-feature-extractor that I can manually train within SB3. It seems that using such a feature extractor has not yet been considered within the rl-baselines3-zoo. Is anyone aware of such efforts?

A preliminary survey of this code base indicates to me that an integration should be rather straight forward. It would require 
1. some kind of registration such that the code of the custom Feature Extractor can be found and named (similar to ALGOS in utils.py or the registrations done in import_envs.py)
2. a slight change to ExperimentManager such that it adds "policy_kwargs" -> "features_extractor_class" based on the str to class mapping implemented in step 1.

I welcome any feedback on where else model creation is touched or where such a registration step for custom feature extractors would be appropriate.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/rl-baselines3-zoo/issues) in the repo
- [X] I have read the [SB3 documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have read the [RL Zoo documentation](https://rl-baselines3-zoo.readthedocs.io)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment] 2023-10-19 17:15
Duplicate of https://github.com/DLR-RM/rl-baselines3-zoo/issues/300, see the two solutions.

**Closed** 2023-10-20 10:34 UTC
Labels: duplicate, question
