### ISSUE TITLE
[feature request] expose NoVel environments; pip installable?

### ISSUE THREAD

**Issue by ikamensh** [DLR-RM/rl-baselines3-zoo#285] opened 2022-09-12 15:10 UTC
Hi,

I wanted to mention a possible usecase of the code in sb3-z: You have the NoVel environments that others can use to verify their recurrent policy implementations. If I understand right, now I have to copy the whole library or some selected files into my project to experiment on these environments, and `import utils.import_envs`.

 It would be ideal to `pip install` something to have those. And/Or have a callable `register_novel_envs`.

Thanks for considering!

**Comment by araffin** [comment] 2022-09-12 16:13
Probably a duplicate of https://github.com/DLR-RM/rl-baselines3-zoo/issues/249, help is welcomed ;)
but yes, for now, you need to copy the folder/files.

**Comment by ikamensh** [comment] 2022-09-13 08:02
by the way, the code references a repo with no license: https://github.com/DLR-RM/rl-baselines3-zoo/blob/38eb59d74c49eaf77d8994fd28d220a9f65a21ee/utils/wrappers.py#L348 - I've requested them to add a license https://github.com/LiuWenlin595/FinalProject/issues/1 but if they don't not sure it's compliant.

**Closed** 2022-10-02 19:01 UTC
Labels: enhancement
