### ISSUE TITLE
Running enjoy.py on existing trained agent throws exception

### ISSUE THREAD

**Issue by amy12xx** [DLR-RM/rl-baselines3-zoo#97] opened 2021-05-26 05:37 UTC
**Describe the bug**
I am trying to directly run one of the trained agents, using the colab notebook linked in the repo, but get an exception printed below.
Link to notebook: https://colab.research.google.com/github/Stable-Baselines-Team/rl-colab-notebooks/blob/sb3/rl-baselines-zoo.ipynb

**Code example**
These are the steps I ran until I hit the error, on colab with GPU:
```
!apt-get install swig cmake ffmpeg freeglut3-dev xvfb
!git clone --recursive https://github.com/DLR-RM/rl-baselines3-zoo
%cd /content/rl-baselines3-zoo/
!pip install -r requirements.txt
!python enjoy.py --algo a2c --env Pendulum-v0 --folder rl-trained-agents/ -n 5000
```

Here's the error stack trace:
```
Loading latest experiment, id=1
Loading running average
with params: {'norm_obs': True, 'norm_reward': False}
Traceback (most recent call last):
  File "enjoy.py", line 225, in <module>
    main()
  File "enjoy.py", line 155, in main
    model = ALGOS[algo].load(model_path, env=env, custom_objects=custom_objects, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/stable_baselines3/common/base_class.py", line 623, in load
    data, params, pytorch_variables = load_from_zip_file(path, device=device, custom_objects=custom_objects)
  File "/usr/local/lib/python3.7/dist-packages/stable_baselines3/common/save_util.py", line 402, in load_from_zip_file
    data = json_to_data(json_data, custom_objects=custom_objects)
  File "/usr/local/lib/python3.7/dist-packages/stable_baselines3/common/save_util.py", line 164, in json_to_data
    deserialized_object = cloudpickle.loads(base64_object)
  File "/usr/local/lib/python3.7/dist-packages/cloudpickle/cloudpickle_fast.py", line 395, in <module>
    class CloudPickler(Pickler):
  File "/usr/local/lib/python3.7/dist-packages/cloudpickle/cloudpickle_fast.py", line 418, in CloudPickler
    dispatch[types.CellType] = _cell_reduce
AttributeError: module 'types' has no attribute 'CellType'
```

**System Info**
Describe the characteristic of your environment:
 * Describe how Stable Baselines3 was installed (pip, docker, source, ...)
 * GPU models and configuration
 * Python version
 * PyTorch version
 * Versions of any other relevant libraries (Pybullet, ...)
Library versions that get installed:
cloudpickle 1.3.0
stable_baselines3 1.1.0a7

**Additional context**
This may be similar to the problem listed here, of a mismatch of cloudpickle version used to save the model, and one being loaded?
> The error AttributeError: module 'types' has no attribute 'CellType' is the result of different minor versions of cloudpickle between the environment where a flow runs and the environment where it was registered.
https://github.com/PrefectHQ/prefect/issues/3148

**Comment by araffin** [comment] 2021-05-26 05:53
Duplicate of https://github.com/DLR-RM/rl-baselines3-zoo/issues/90

i would appreciate a PR that sets a minimum version for cloudpickle in the requirements ;)

**Comment by araffin** [comment] 2021-05-26 11:00
> Yes, I can add cloudpickle >= 1.5.0. That seems to be the earliest one that does not break. I don't know how future proof this would be though.

well, at least it will be better than what we have currently ^^"

**Closed** 2021-05-27 11:22 UTC
