### ISSUE TITLE
[question] Cannot enjoy the trained agents. 

### ISSUE THREAD

**Issue by Litao917** [DLR-RM/rl-baselines3-zoo#18] opened 2020-06-03 13:13 UTC
After cloning the rl-baselines3-zoo, I was trying to train my own agent.
By :
**python train.py --algo algo_name --env env_id**
After that, I used
**python enjoy.py --algo td3 --env AntBulletEnv-v0 -f logs/**
However I got the following problem

```
Loading latest experiment, id=2 pybullet build time: Jun 2 2020 06:49:02 
/home/dell/gym/gym/logger.py:30: UserWarning: 
WARN: Box bound precision lowered by casting to float32 warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow')) 
Process ForkServerProcess-1: Traceback (most recent call last):
 
File "/home/dell/anaconda3/lib/python3.8/multiprocessing/process.py", 
line 315, in _bootstrap self.run() 

File "/home/dell/anaconda3/lib/python3.8/multiprocessing/process.py", 
line 108, in run self._target(*self._args, **self._kwargs) File "/home/dell/stable-baselines3/stable_baselines3/common/vec_env/subproc_vec_env.py", 
line 42, in _worker 
**raise NotImplementedError
 NotImplemented Error**

 Traceback (most recent call last): File "enjoy.py", 
line 201, in <module> main() File "enjoy.py", line 116, in main
 model = ALGOS[algo].load(model_path, env=env) 
File "/home/dell/stable-baselines3/stable_baselines3/common/base_class.py",
 line 362, in load model._setup_model() 
File "/home/dell/stable-baselines3/stable_baselines3/td3/td3.py",
 line 95, in _setup_model super(TD3, self)._setup_model() 
File "/home/dell/stable-baselines3/stable_baselines3/common/base_class.py", 
line 729, in _setup_model self.set_random_seed(self.seed)
 File "/home/dell/stable-baselines3/stable_baselines3/common/base_class.py", 
line 461, in set_random_seed self.env.seed(seed) File "/home/dell/stable-baselines3/stable_baselines3/common/vec_env/subproc_vec_env.py",
 line 112, in seed return [remote.recv() for remote in self.remotes] 
File "/home/dell/stable-baselines3/stable_baselines3/common/vec_env/subproc_vec_env.py", 
line 112, in <listcomp> return [remote.recv() for remote in self.remotes] File "/home/dell/anaconda3/lib/python3.8/multiprocessing/connection.py", 
line 250, in recv buf = self._recv_bytes() 
File "/home/dell/anaconda3/lib/python3.8/multiprocessing/connection.py", 
line 414, in _recv_bytes buf = self._recv(4) 
File "/home/dell/anaconda3/lib/python3.8/multiprocessing/connection.py", 
line 383, in _recv 
**raise EOFError 
EOFError**`

```
**System Info**

* Stable Baselines3 was installed by pip
* Ubuntu 18.04
* Python 3.8.3
* PyTorch 1.5.0
* Gym 0.17.2
* Pybullet 2.8.1
 * 2* Nvidia RTX 2080TI CUDA 10.2 

I appreciate your help.  Thank you in advance.

**Comment by araffin** [comment] 2020-06-03 13:21
Hello,

Could you reformat your traceback using markdown codeblock? (cf issue template)

**Comment by Litao917** [comment] 2020-06-03 14:27
> Hello,
> 
> Could you reformat your traceback using markdown codeblock? (cf issue template)

I have reformatted the traceback using markdown codeblock

**Comment by araffin** [comment] 2020-06-03 15:57
This look like a python issue.
You can try two things:
- change the `start_method` to "fork" for the `SubProcVecenv` (cf doc)
- change the environment used to `DummyVecEnv`

**Comment by Litao917** [comment] 2020-06-04 06:03
> This look like a python issue.
> You can try two things:
> 
> * change the `start_method` to "fork" for the `SubProcVecenv` (cf doc)
> * change the environment used to `DummyVecEnv`

Hi araffin,
Thank you for your suggestions. I just tried setting the start_method to fork by using 
```
import multiprocessing as mp
.....

if __name__ == '__main__':
    mp.set_start_method('fork')
    main()
```

as well as  change the line 71 of subporc_vec_env.py to 
```
 def __init__(self, env_fns, start_method='fork'):
```
However, I got the following errors
```
Loading latest experiment, id=1
pybullet build time: Jun  2 2020 06:49:02
/home/dell/gym/gym/logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
Loading running average
with params: {'norm_obs': True, 'norm_reward': False}
Process ForkProcess-1:
Traceback (most recent call last):
  File "/home/dell/anaconda3/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/dell/anaconda3/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dell/stable-baselines3/stable_baselines3/common/vec_env/subproc_vec_env.py", line 42, in _worker
    raise NotImplementedError
NotImplementedError
Traceback (most recent call last):
  File "enjoy.py", line 204, in <module>
    main()
  File "enjoy.py", line 117, in main
    model = ALGOS[algo].load(model_path, env=env)
  File "/home/dell/stable-baselines3/stable_baselines3/common/base_class.py", line 362, in load
    model._setup_model()
  File "/home/dell/stable-baselines3/stable_baselines3/ppo/ppo.py", line 125, in _setup_model
    self.set_random_seed(self.seed)
  File "/home/dell/stable-baselines3/stable_baselines3/common/base_class.py", line 461, in set_random_seed
    self.env.seed(seed)
  File "/home/dell/stable-baselines3/stable_baselines3/common/vec_env/base_vec_env.py", line 266, in seed
    return self.venv.seed(seed)
  File "/home/dell/stable-baselines3/stable_baselines3/common/vec_env/base_vec_env.py", line 266, in seed
    return self.venv.seed(seed)
  File "/home/dell/stable-baselines3/stable_baselines3/common/vec_env/subproc_vec_env.py", line 112, in seed
    return [remote.recv() for remote in self.remotes]
  File "/home/dell/stable-baselines3/stable_baselines3/common/vec_env/subproc_vec_env.py", line 112, in <listcomp>
    return [remote.recv() for remote in self.remotes]
  File "/home/dell/anaconda3/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/home/dell/anaconda3/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/home/dell/anaconda3/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
```


Moreover, I'm sorry I don't know how to correctly change the environment to `DummyVecEnv`. Would you please give any further suggestion? Thanks a lot.

**Comment by araffin** [comment] 2020-06-04 07:44
I could reproduce the bug in a google colab: https://colab.research.google.com/drive/1KGCOro2y37_Ptzb4240xKoVEY2FzYUVR?usp=sharing

I will look into it.

**Comment by araffin** [comment] 2020-06-04 07:51
after looking more closely at the traceback, this is due to 
```
  File "/usr/local/lib/python3.6/dist-packages/stable_baselines3/common/base_class.py", line 465, in set_random_seed
    self.env.seed(seed)
```
I will try to push a fix on SB3 soon.

**Comment by araffin** [comment] 2020-06-04 07:53
>Moreover, I'm sorry I don't know how to correctly change the environment to DummyVecEnv. Would you please give any further suggestion? 

Change line 235 of `utils.py` from `SubprocVecEnv` to `DummyVecEnv`

**Comment by Litao917** [comment] 2020-06-04 08:18
After changing` SubprocVecEnv `to `DummyVecEnv`, I got
```
Loading latest experiment, id=1
pybullet build time: Jun  2 2020 06:49:02
/home/dell/gym/gym/logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
Loading running average
with params: {'norm_obs': True, 'norm_reward': False}
Traceback (most recent call last):
  File "enjoy.py", line 204, in <module>
    main()
  File "enjoy.py", line 131, in main
    action, state = model.predict(obs, state=state, deterministic=deterministic)
  File "/home/dell/stable-baselines3/stable_baselines3/common/base_class.py", line 321, in predict
    return self.policy.predict(observation, state, mask, deterministic)
  File "/home/dell/stable-baselines3/stable_baselines3/common/policies.py", line 225, in predict
    actions = self._predict(observation, deterministic=deterministic)
  File "/home/dell/stable-baselines3/stable_baselines3/ppo/policies.py", line 278, in _predict
    return distribution.get_actions(deterministic=deterministic)
  File "/home/dell/stable-baselines3/stable_baselines3/common/distributions.py", line 59, in get_actions
    return self.sample()
  File "/home/dell/stable-baselines3/stable_baselines3/common/distributions.py", line 551, in sample
    noise = self.get_noise(self._latent_sde)
  File "/home/dell/stable-baselines3/stable_baselines3/common/distributions.py", line 542, in get_noise
    return th.mm(latent_sde, self.exploration_mat)
RuntimeError: Expected object of device type cuda but got device type cpu for argument #2 'mat2' in call to _th_mm
```

I'll follow the update. Thanks!  araffin!

**Comment by araffin** [comment] 2020-06-04 08:29
Did you train on a CUDA enabled device and test on cpu?

I assume passing `--deterministic` would solve the issue here.

another posssible quick fix (this will hide cuda and force cpu mode):
```
export CUDA_VISIBLE_DEVICES=
```
to re-enable cuda:
```
unset CUDA_VISIBLE_DEVICES
```

Thanks for reporting those issues. Saving/loading with CUDA/cpu is hard to test with Github CI unfortunately.

**Comment by Litao917** [comment] 2020-06-04 09:16
> Did you train on a CUDA enabled device and test on cpu?
> 
> I assume passing `--deterministic` would solve the issue here.
> 
> another posssible quick fix (this will hide cuda and force cpu mode):
> 
> ```
> export CUDA_VISIBLE_DEVICES=
> ```
> 
> to re-enable cuda:
> 
> ```
> unset CUDA_VISIBLE_DEVICES
> ```
> 
> Thanks for reporting those issues. Saving/loading with CUDA/cpu is hard to test with Github CI unfortunately.

I doublechecked the device thing. The agent is trained on CUDA and tested on CUDA as well. 
Besides, after re-enable CUDA by `unset CUDA_VISIBLE_DEVICES`,  I got the same issue. 
I tried switch line 62 of base_class.py
`                 device: Union[th.device, str] = 'auto',`  
to 
`                 device: Union[th.device, str] = 'cuda',`

The issue still appears. 
What should I do to fix the device problem?

**Comment by araffin** [comment] 2020-06-04 09:21
> What should I do to fix the device problem?

you can disable CUDA (as mentioned before) or do 
```
python enjoy.py --algo ppo --env AntBulletEnv-v0 -f logs --deterministic
```
for now, I will also try to fix the issue soon (https://github.com/DLR-RM/stable-baselines3/issues/44).
Anyway, as mentioned in the documentation, you should use the deterministic version at test time for control problems.

**Comment by araffin** [comment] 2020-06-04 09:23
The first fix is now pushed, you can update your SB3 version ;)

**Comment by Litao917** [comment] 2020-06-04 10:01
Thank you for your help. Nice work!

**Comment by araffin** [comment] 2020-06-04 10:04
I fixed the second issue here (one line fix luckily): https://github.com/DLR-RM/stable-baselines3/pull/45

you can add `model.policy.reset_noise()` in the `enjoy.py` too, but as mentioned before, please use deterministic mode for testing on continuous control environments.

**Comment by araffin** [comment] 2020-06-08 09:18
The fix is merged with master and I just released a new version on PyPi.
Please upgrade your SB3 version and it should work ;)

**Closed** 2020-06-08 09:18 UTC
Labels: bug, question

**Comment by ycps** [comment] 2020-06-09 23:37
Hi, I'm not sure if I'm doing something wrong, but I recently upgraded both SB3 and SB3-zoo but still got the same error after trying to enjoy a SAC agent in `HumanoidBulletEnv-v0` with `--deterministic`:

```
$ venv/py36/bin/python3.6m enjoy.py --verbose 2 --algo sac --env HumanoidBulletEnv-v0 -f logs/ --exp-id 1 --load-best --deterministic

pybullet build time: May  8 2020 21:47:49
/home/user/venv/py36/lib/python3.6/site-packages/gym/logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
Loading running average
with params: {'norm_obs': True, 'norm_reward': False}
Process ForkServerProcess-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/venv/py36/lib/python3.6/site-packages/stable_baselines3/common/vec_env/subproc_vec_env.py", line 42, in _worker
    raise NotImplementedError
NotImplementedError
Traceback (most recent call last):
  File "enjoy.py", line 201, in <module>
    main()
  File "enjoy.py", line 116, in main
    model = ALGOS[algo].load(model_path, env=env)
  File "/home/user/venv/py36/lib/python3.6/site-packages/stable_baselines3/common/base_class.py", line 366, in load
    model._setup_model()
  File "/home/user/venv/py36/lib/python3.6/site-packages/stable_baselines3/sac/sac.py", line 116, in _setup_model
    super(SAC, self)._setup_model()
  File "/home/user/venv/py36/lib/python3.6/site-packages/stable_baselines3/common/base_class.py", line 744, in _setup_model
    self.set_random_seed(self.seed)
  File "/home/user/venv/py36/lib/python3.6/site-packages/stable_baselines3/common/base_class.py", line 465, in set_random_seed
    self.env.seed(seed)
  File "/home/user/venv/py36/lib/python3.6/site-packages/stable_baselines3/common/vec_env/base_vec_env.py", line 266, in seed
    return self.venv.seed(seed)
  File "/home/user/venv/py36/lib/python3.6/site-packages/stable_baselines3/common/vec_env/base_vec_env.py", line 266, in seed
    return self.venv.seed(seed)
  File "/home/user/venv/py36/lib/python3.6/site-packages/stable_baselines3/common/vec_env/subproc_vec_env.py", line 112, in seed
    return [remote.recv() for remote in self.remotes]
  File "/home/user/venv/py36/lib/python3.6/site-packages/stable_baselines3/common/vec_env/subproc_vec_env.py", line 112, in <listcomp>
    return [remote.recv() for remote in self.remotes]
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
```
As suggested, changing from `SubprocVecEnv` to `DummyVecEnv` in `utils.py` works, but (as expected) the 'enjoyment' is no longer rendered.

**System Info**
 * SB3 installed by `pip`, SB3-zoo via `git`
 * Python 3.6.9
 * PyTorch 1.5.0
 * Gym 0.17.2
 * Pybullet 2.8.1

**Comment by araffin** [comment] 2020-06-10 08:20
> I recently upgraded both SB3 and SB3-zoo 

Please do `pip install git+https://github.com/DLR-RM/stable-baselines3` (cf doc) or enable pre-release install.
The Stable-Baselines version should be 0.7.0a1
