### ISSUE TITLE
[Bug]: FrameStack and VecNormalize

### ISSUE THREAD

**Issue by suargi** [DLR-RM/rl-baselines3-zoo#480] opened 2024-12-16 11:00 UTC
### 🐛 Bug

There is a bug when using vecnormalize and framestack.
Such bug was mentioned in here https://github.com/DLR-RM/stable-baselines3/issues/693 and seems to be present in SB3-zoo.

### To Reproduce

```shell
python train.py --env LunarLanderContinuous-v3 --algo sac -params frame_stack:2 normalize:True
```

### Relevant log output / Error message

```shell
Traceback (most recent call last):
  File "rl-baselines3-zoo/train.py", line 4, in <module>
    train()
  File "rl-baselines3-zoo/rl_zoo3/train.py", line 272, in train
    exp_manager.learn(model)
  File "rl-baselines3-zoo/rl_zoo3/exp_manager.py", line 240, in learn
    model.learn(self.n_timesteps, **kwargs)
  File "stable-baselines3/stable_baselines3/sac/sac.py", line 307, in learn
    return super().learn(
           ^^^^^^^^^^^^^^
  File "stable-baselines3/stable_baselines3/common/off_policy_algorithm.py", line 328, in learn
    rollout = self.collect_rollouts(
              ^^^^^^^^^^^^^^^^^^^^^^
  File "stable-baselines3/stable_baselines3/common/off_policy_algorithm.py", line 584, in collect_rollouts
    self._store_transition(replay_buffer, buffer_actions, new_obs, rewards, dones, infos)  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "stable-baselines3/stable_baselines3/common/off_policy_algorithm.py", line 501, in _store_transition
    replay_buffer.add(
  File "stable-baselines3/stable_baselines3/common/buffers.py", line 274, in add
    self.observations[self.pos] = np.array(obs)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^
ValueError: could not broadcast input array from shape (1,8) into shape (1,16)


Problem originates in `off_policy_algorithm.py` as we do not copy self._last_obs into self._last_original_obs
```

### System Info

Using master version from SB3 and SB3-zoo

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/rl-baselines3-zoo/issues) in the repo
- [X] I have read the [SB3 documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have read the [RL Zoo documentation](https://rl-baselines3-zoo.readthedocs.io)
- [X] I have provided a [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014) example to reproduce the bug
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment] 2024-12-16 14:27
Duplicate of https://github.com/DLR-RM/stable-baselines3/issues/693

**Comment by suargi** [comment] 2024-12-17 10:16
The solution is to use `vec_env_wrapper` in the configuration. For example:
```
LunarLanderContinuous-v3:
   vec_env_wrapper:
     - stable_baselines3.common.vec_env.VecFrameStack:
           n_stack: 2
   normalize: True
   n_timesteps: !!float 5e5
   ...
```

This will normalize the environment and will use frame stack.

Some questions:
- If we use `env_wrapper` instead of `vec_env_wrapper` it throws the error:
`AttributeError: 'Monitor' object has no attribute 'num_envs'`
- How can we modify `n_stack` from the shell:
`python train.py --env LunarLanderContinuous-v3 --algo sac -params ...`?

**Closed** 2024-12-17 11:16 UTC
Labels: bug, duplicate

**Comment by araffin** [comment] 2024-12-17 11:44
> it throws the error:

yes, env wrapper is for gym env, so you need to use gym wrapper here (not the vec wrapper which is for SB3 vec env)

> from the shell:

https://github.com/DLR-RM/rl-baselines3-zoo/blob/506bb7aa40e9d90e997580a369f2e9bf64abe594/tests/test_wrappers.py#L47

probably easier:

```
python train.py --env LunarLanderContinuous-v3 --algo sac -params vec_env_wrapper:'{\"stable_baselines3.common.vec_env.VecFrameStack\":dict(n_stack=4)}'
```
